//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labo.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Labo.Common.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; embedded resource couldn&apos;t be found..
        /// </summary>
        internal static string AssemblyUtils_GetEmbededResourceString_embedded_resource_not_found {
            get {
                return ResourceManager.GetString("AssemblyUtils_GetEmbededResourceString_embedded_resource_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred While Changing Value.
        /// </summary>
        internal static string ConvertUtils_GetConversionException_An_Error_Occurred_While_Changing_Value {
            get {
                return ResourceManager.GetString("ConvertUtils_GetConversionException_An_Error_Occurred_While_Changing_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred While Getting Names and Values of Enum Type.
        /// </summary>
        internal static string EnumUtils_GetNamesAndValues_An_Error_Occurred_While_Getting_Names_and_Values_of_Enum_Type {
            get {
                return ResourceManager.GetString("EnumUtils_GetNamesAndValues_An_Error_Occurred_While_Getting_Names_and_Values_of_E" +
                        "num_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underlying Type Must Be Enum.
        /// </summary>
        internal static string EnumUtils_GetNamesAndValues_Underlying_Type_Must_Be_Enum {
            get {
                return ResourceManager.GetString("EnumUtils_GetNamesAndValues_Underlying_Type_Must_Be_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred While Parsing Enum Value.
        /// </summary>
        internal static string EnumUtils_Parse_An_Error_Occurred_While_Parsing_Enum_Value {
            get {
                return ResourceManager.GetString("EnumUtils_Parse_An_Error_Occurred_While_Parsing_Enum_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred While Creating Instance.
        /// </summary>
        internal static string ReflectionHelper_CreateInstance_An_Error_Occurred_While_Creating_Instance {
            get {
                return ResourceManager.GetString("ReflectionHelper_CreateInstance_An_Error_Occurred_While_Creating_Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred While Getting Property Value.
        /// </summary>
        internal static string ReflectionHelper_GetPropertyValue_An_Error_Occurred_While_Getting_Property_Value {
            get {
                return ResourceManager.GetString("ReflectionHelper_GetPropertyValue_An_Error_Occurred_While_Getting_Property_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred While Setting Property Value.
        /// </summary>
        internal static string ReflectionHelper_SetPropertyValue_An_Error_Occurred_While_Setting_Property_Value {
            get {
                return ResourceManager.GetString("ReflectionHelper_SetPropertyValue_An_Error_Occurred_While_Setting_Property_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to element.Attributes is null.
        /// </summary>
        internal static string XmlUtils_AppendAttribute_element_Attributes_is_null {
            get {
                return ResourceManager.GetString("XmlUtils_AppendAttribute_element_Attributes_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to element.OwnerDocument is null.
        /// </summary>
        internal static string XmlUtils_AppendAttribute_element_OwnerDocument_is_null {
            get {
                return ResourceManager.GetString("XmlUtils_AppendAttribute_element_OwnerDocument_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parentNode.OwnerDocument is null.
        /// </summary>
        internal static string XmlUtils_AppendNodeToParent_parentNode_OwnerDocument_is_null {
            get {
                return ResourceManager.GetString("XmlUtils_AppendNodeToParent_parentNode_OwnerDocument_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetNodeProperty Error.
        /// </summary>
        internal static string XmlUtils_GetNodeProperty_Error {
            get {
                return ResourceManager.GetString("XmlUtils_GetNodeProperty_Error", resourceCulture);
            }
        }
    }
}
