//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labo.Common.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Labo.Common.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; embedded resource couldn&apos;t be found..
        /// </summary>
        internal static string AssemblyUtils_GetEmbededResourceString_embedded_resource_not_found {
            get {
                return ResourceManager.GetString("AssemblyUtils_GetEmbededResourceString_embedded_resource_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Authenticated.
        /// </summary>
        internal static string AuthenticationAspect_Not_Authenticated {
            get {
                return ResourceManager.GetString("AuthenticationAspect_Not_Authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Size of Cookie must be {0} bytes.
        /// </summary>
        internal static string CookieClientStorage_UpdateStorage_Max_Size_of_Cookie {
            get {
                return ResourceManager.GetString("CookieClientStorage_UpdateStorage_Max_Size_of_Cookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; is not found..
        /// </summary>
        internal static string CreateIncludeScript_File_not_found {
            get {
                return ResourceManager.GetString("CreateIncludeScript_File_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} must declare an empty constructor (the constructor may be private, internal, protected, protected internal, or public)..
        /// </summary>
        internal static string DynamicMethodCompiler_The_type_must_declare_an_empty_constructor {
            get {
                return ResourceManager.GetString("DynamicMethodCompiler_The_type_must_declare_an_empty_constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Denied.
        /// </summary>
        internal static string ExceptionFormatter_GetMachineName_Permission_Denied {
            get {
                return ResourceManager.GetString("ExceptionFormatter_GetMachineName_Permission_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access failed.
        /// </summary>
        internal static string ExceptionFormatter_WriteReflectionInfo_Access_failed {
            get {
                return ResourceManager.GetString("ExceptionFormatter_WriteReflectionInfo_Access_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Resource Type Not Supported.
        /// </summary>
        internal static string GetContentType_Resource_Type_Not_Supported {
            get {
                return ResourceManager.GetString("GetContentType_Resource_Type_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpContext.Current is null for the current call.
        /// </summary>
        internal static string HttpContext_Current_is_null {
            get {
                return ResourceManager.GetString("HttpContext_Current_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; is not found..
        /// </summary>
        internal static string MinifyAndCombineResourceProcessor_File_not_found {
            get {
                return ResourceManager.GetString("MinifyAndCombineResourceProcessor_File_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Resource Type Not Supported.
        /// </summary>
        internal static string MinifyAndCombineResourceProcessor_MinifyResource_Resource_Type_Not_Supported {
            get {
                return ResourceManager.GetString("MinifyAndCombineResourceProcessor_MinifyResource_Resource_Type_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Service &apos;{1}&apos; Method is Called.
        /// </summary>
        internal static string PerformanceTraceAspect_Service_Method_is_Called {
            get {
                return ResourceManager.GetString("PerformanceTraceAspect_Service_Method_is_Called", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RavenDB ConnectionString Cannot be empty. Please check your configuration data..
        /// </summary>
        internal static string RavenDBProvider_RavenDB_ConnectionString_Cannot_be_empty {
            get {
                return ResourceManager.GetString("RavenDBProvider_RavenDB_ConnectionString_Cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred While Creating Instance.
        /// </summary>
        internal static string ReflectionHelper_CreateInstance_An_Error_Occurred_While_Creating_Instance {
            get {
                return ResourceManager.GetString("ReflectionHelper_CreateInstance_An_Error_Occurred_While_Creating_Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred While Getting Property Value.
        /// </summary>
        internal static string ReflectionHelper_GetPropertyValue_An_Error_Occurred_While_Getting_Property_Value {
            get {
                return ResourceManager.GetString("ReflectionHelper_GetPropertyValue_An_Error_Occurred_While_Getting_Property_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred While Setting Property Value.
        /// </summary>
        internal static string ReflectionHelper_SetPropertyValue_An_Error_Occurred_While_Setting_Property_Value {
            get {
                return ResourceManager.GetString("ReflectionHelper_SetPropertyValue_An_Error_Occurred_While_Setting_Property_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; method of &apos;{1}&apos; class must be virtual in order to apply &apos;{2}&apos; interceptor.
        /// </summary>
        internal static string RegistrationBase_methods_of_the_class_must_be_virtual {
            get {
                return ResourceManager.GetString("RegistrationBase_methods_of_the_class_must_be_virtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; image has no extension..
        /// </summary>
        internal static string ResourceManagerProcessor__image_has_no_extension {
            get {
                return ResourceManager.GetString("ResourceManagerProcessor__image_has_no_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image path specified..
        /// </summary>
        internal static string ResourceManagerProcessor_No_image_path_specified {
            get {
                return ResourceManager.GetString("ResourceManagerProcessor_No_image_path_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Resource Path in the QueryString.
        /// </summary>
        internal static string ResourceManagerProcessor_No_Resource_Path_in_the_QueryString {
            get {
                return ResourceManager.GetString("ResourceManagerProcessor_No_Resource_Path_in_the_QueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not have ServiceAttribute.
        /// </summary>
        internal static string ServiceInterceptor_GetServiceInterfaceMethodInfo_does_not_have_ServiceAttribute {
            get {
                return ResourceManager.GetString("ServiceInterceptor_GetServiceInterfaceMethodInfo_does_not_have_ServiceAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current handler &apos;{0}&apos; doesn&apos;t implement IRequiresSessionState so Session is null for the Current HttpContext.
        /// </summary>
        internal static string SessionState_Current_handler_not_implement_IRequiresSessionState {
            get {
                return ResourceManager.GetString("SessionState_Current_handler_not_implement_IRequiresSessionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session is null for the Current HttpContext.
        /// </summary>
        internal static string SessionState_Session_is_null_for_the_Current_HttpContext {
            get {
                return ResourceManager.GetString("SessionState_Session_is_null_for_the_Current_HttpContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Validation Exception:.
        /// </summary>
        internal static string TextExceptionFormatter_Entity_Validation_Exception {
            get {
                return ResourceManager.GetString("TextExceptionFormatter_Entity_Validation_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info:.
        /// </summary>
        internal static string TextExceptionFormatter_WriteAdditionalInfo_Additional_Info {
            get {
                return ResourceManager.GetString("TextExceptionFormatter_WriteAdditionalInfo_Additional_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception of type &apos;{0}&apos; occurred and was caught..
        /// </summary>
        internal static string TextExceptionFormatter_WriteDescription_exception_occurred_caught {
            get {
                return ResourceManager.GetString("TextExceptionFormatter_WriteDescription_exception_occurred_caught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Exception.
        /// </summary>
        internal static string TextExceptionFormatter_WriteException_Inner_Exception {
            get {
                return ResourceManager.GetString("TextExceptionFormatter_WriteException_Inner_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type : {0}.
        /// </summary>
        internal static string TextExceptionFormatter_WriteExceptionType {
            get {
                return ResourceManager.GetString("TextExceptionFormatter_WriteExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help link : {0}.
        /// </summary>
        internal static string TextExceptionFormatter_WriteHelpLink_Help_link {
            get {
                return ResourceManager.GetString("TextExceptionFormatter_WriteHelpLink_Help_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message : {0}.
        /// </summary>
        internal static string TextExceptionFormatter_WriteMessage_Message {
            get {
                return ResourceManager.GetString("TextExceptionFormatter_WriteMessage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source : {0}.
        /// </summary>
        internal static string TextExceptionFormatter_WriteSource_Source {
            get {
                return ResourceManager.GetString("TextExceptionFormatter_WriteSource_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace.
        /// </summary>
        internal static string TextExceptionFormatter_WriteStackTrace_Stack_Trace {
            get {
                return ResourceManager.GetString("TextExceptionFormatter_WriteStackTrace_Stack_Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stack trace is unavailable..
        /// </summary>
        internal static string TextExceptionFormatter_WriteStackTrace_The_stack_trace_is_unavailable {
            get {
                return ResourceManager.GetString("TextExceptionFormatter_WriteStackTrace_The_stack_trace_is_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Ended At {1}. ({2} ms).
        /// </summary>
        internal static string TraceContext_OnEnd_Ended_At_x_ms {
            get {
                return ResourceManager.GetString("TraceContext_OnEnd_Ended_At_x_ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Started At {1}..
        /// </summary>
        internal static string TraceContext_OnStart_Started_At {
            get {
                return ResourceManager.GetString("TraceContext_OnStart_Started_At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentContext must be called in a TraceScope.
        /// </summary>
        internal static string TraceScopeContextManager_CurrentContext_is_null {
            get {
                return ResourceManager.GetString("TraceScopeContextManager_CurrentContext_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentScopeEntry must be called inside a Trace Scope.
        /// </summary>
        internal static string TraceScopeContextManager_CurrentScopeEntry_must_be_called_inside_a_Trace_Scope {
            get {
                return ResourceManager.GetString("TraceScopeContextManager_CurrentScopeEntry_must_be_called_inside_a_Trace_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to element.OwnerDocument is null.
        /// </summary>
        internal static string XmlUtils_AppendAttribute_element_OwnerDocument_is_null {
            get {
                return ResourceManager.GetString("XmlUtils_AppendAttribute_element_OwnerDocument_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parentNode.OwnerDocument is null.
        /// </summary>
        internal static string XmlUtils_AppendNodeToParent_parentNode_OwnerDocument_is_null {
            get {
                return ResourceManager.GetString("XmlUtils_AppendNodeToParent_parentNode_OwnerDocument_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetNodeProperty Error.
        /// </summary>
        internal static string XmlUtils_GetNodeProperty_Error {
            get {
                return ResourceManager.GetString("XmlUtils_GetNodeProperty_Error", resourceCulture);
            }
        }
    }
}
